# Generated by Django 2.2.6 on 2019-11-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpyou', '0003_auto_20191103_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_participantes',
            name='cpf',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tb_participantes',
            name='telefone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tb_psicologos',
            name='cpf',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tb_psicologos',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
