# Generated by Django 2.2.6 on 2019-11-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpyou', '0004_auto_20191104_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_psicologos',
            name='registro_crp',
            field=models.IntegerField(),
        ),
    ]
