# Generated by Django 2.2.6 on 2019-11-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpyou', '0005_auto_20191104_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='td_categorias',
            old_name='nome',
            new_name='nome_categoria',
        ),
    ]
